# Generated by Django 5.2.17 on 2026-08-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleevent",
            name="link_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Необязательная ссылка на подробности/внешний ресурс",
            ),
        ),
    ]
