# Generated by Django 5.2.17 on 2026-08-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_publish_hide_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='hide_at',
            field=models.DateTimeField(blank=True, help_text='Необязательно — после этого момента новость скрывается от учеников', null=True),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='publish_at',
            field=models.DateTimeField(help_text='Дата и время рассылки — с этого момента новость видна ученикам'),
        ),
    ]
