# Generated by Django 5.2.17 on 2026-08-26 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_scheduleevent_hide_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
