# Generated by Django 5.2.17 on 2026-08-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="chats/audio/"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
