# Generated by Django 5.2.17 on 2026-08-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InviteCode",
        ),
    ]
