# Generated by Django 5.2.17 on 2026-09-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='access_reminder_sent_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
