# Generated by Django 5.2.17 on 2026-08-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_description_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/audio/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/posters/'),
        ),
    ]
