# Generated by Django 5.2.17 on 2026-08-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_video_audio_file_lesson_video_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video_timestamp_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
