# Generated by Django 5.2.17 on 2026-08-26 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_comment_video_timestamp_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
