# Generated by Django 5.2.17 on 2026-08-26 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_material_favorited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
