# Generated by Django 5.2.17 on 2026-09-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 означает без ограничений'),
        ),
        migrations.AddField(
            model_name='test',
            name='require_lessons_watched',
            field=models.BooleanField(default=True),
        ),
    ]
